iconclass=['more', 'check', 'lock', 'emoji', 'time', 'book', 'menu', 'avatar', 'close', 'arrow_forward', 'home', 'add', 'arrow_backward', 'date_range', 'favorite', 'location_crosshair', 'star', 'share', 'play', 'pause', 'search', 'sliders', 'facebook', 'bluetooth', 'chat', 'globe', 'minus', 'national_flag', 'list', 'refresh', 'layers', 'weather', 'location', 'delete', 'volume', 'info', 'switcher', 'swap', 'notifications', 'bookmark', 'thumbs_up', 'explore', 'email', 'arrow_upward', 'microphone', 'font', 'redo', 'visibility', 'cart', 'settings', 'edit', 'save', 'expand_more', 'launch', 'warning', 'follow', 'photo', 'undo', 'flight', 'shop', 'attach_file', 'music', 'expand_less', 'help', 'send', 'navigation', 'videocam', 'playlist', 'wallpaper', 'group', 'gift', 'filter', 'dialpad', 'call', 'file_download', 'dashboard', 'copy', 'twitter', 'filter_list', 'arrow_downward', 'compare', 'power', 'label', 'description', 'build', 'av_rewind', 'av_forward', 'network_wifi', 'reply', 'folder', 'skip_next', 'skip_previous', 'history', 'zoom_out', 'flash', 'fullscreen', 'repeat', 'thumbs_down']
basicClass=['Web View', 'Advertisement', 'Toolbar', 'Text', 'Icon', 'Image', 'List Item', 'Card', 'Text Button', 'Input', 'Radio Button', 'Modal', 'Drawer', 'Background Image', 'Map View', 'On/Off Switch', 'Multi-Tab', 'Button Bar', 'Pager Indicator', 'Checkbox', 'Slider', 'Date Picker', 'Bottom Navigation', 'Video', 'Number Stepper']


element_mapper={'arrow_backward':0, 'close':1,'avatar':2,'check':3,'Checkbox':3,'arrow_forward':4,'menu':5,'play':6,'add':7,'search':8,'settings':9,
'share':10,'Slider':11,'On/Off Switch':12,'star':14,'home':15,'photo':16,'email':17,'Text':18,'Text Button':19,'Image':20, 'Background Image':20,
'Radio Button':21,'Date Picker':22, 'Map View':23,'Number Stepper':24,'Video':25,'Input':26,'more':27,'favorite':28,'refresh':29,
'info':30,'edit':31,'chat':32,'expand_more':33,'help':34,'facebook':35,'volume':36,'pause':37,'microphone':38,'delete':39,'notifications':40,'filter_list':41,
 'twitter':42, 'location_crosshair':43,'bookmark':44,'emoji':45,'sliders':46,'call':47,'minus':48,'file_download':49,'cart':50,'list':51,'undo':52}

